require("config.options")
require("config.keymaps")
-- require("config.session")
require("config.statusline")
require("config.diagnostics")
require("config.autocmds")
require("config.lsp")
require("config.ui2")
--require("config.colors").colorscheme()
